/**
 * Standardized error codes for the application
 *
 * Format: RESOURCE_ERROR_TYPE
 * Example: USER_NOT_FOUND, PRODUCT_ALREADY_EXISTS
 */
export enum ErrorCodes {
  // General validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND',
  CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
  FILE_NOT_PROVIDED = 'FILE_NOT_PROVIDED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  UPLOAD_ERROR = 'UPLOAD_ERROR',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_NOT_ACTIVE = 'PRODUCT_NOT_ACTIVE',
  INVALID_AUCTION_DATES = 'INVALID_AUCTION_DATES',
  PRODUCT_NOT_AVAILABLE = 'PRODUCT_NOT_AVAILABLE',
  PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_OFFLINE = 'PRODUCT_OFFLINE',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  
  // Auction related error codes
  AUCTION_NOT_FOUND = 'AUCTION_NOT_FOUND',
  AUCTION_NOT_ACTIVE = 'AUCTION_NOT_ACTIVE',
  AUCTION_NOT_STARTED = 'AUCTION_NOT_STARTED',
  AUCTION_ENDED = 'AUCTION_ENDED',
  CANNOT_BID_OWN_AUCTION = 'CANNOT_BID_OWN_AUCTION',
  BID_TOO_LOW = 'BID_TOO_LOW',
  AUCTION_HAS_BIDS = 'AUCTION_HAS_BIDS',
  PRODUCT_ALREADY_IN_AUCTION = 'PRODUCT_ALREADY_IN_AUCTION',
  PRODUCT_NOT_AUCTION_TYPE = 'PRODUCT_NOT_AUCTION_TYPE',
  PRODUCT_IN_AUCTION = 'PRODUCT_IN_AUCTION',
  
  // Contract related error codes
  CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND',
  INVALID_CONTRACT_PRODUCT = 'INVALID_CONTRACT_PRODUCT',
}
